package ohnosequences.sbt

import sbt._
import Keys._

import sbtrelease._
import ReleaseStateTransformations._
import ReleasePlugin._
import ReleaseKeys._

import laughedelic.literator.plugin.LiteratorPlugin._

object ApiDocsGeneration {

  lazy val genMarkdownDocsForRelease: ReleaseStep = { st: State =>
    val extracted = Project.extract(st)
    val ref = extracted.get(thisProjectRef)
    val newSt = extracted.runAggregated(Literator.generateDocs in ref, st)
    extracted get versionControlSystem match { 
        case None => sys.error("No version control system is set!")
        case Some(vcs) => if (vcs.status.!!.trim.nonEmpty) {
          val files = extracted get Literator.docsOutputDirs
          vcs.add(files.map(_.getAbsolutePath): _*) ! st.log
          vcs.commit("Autogenerated markdown documentation") ! st.log
        }
    }
    newSt
  }

  lazy val genApiDocsForRelease: ReleaseStep = { st: State =>
    val extracted = Project.extract(st)
    val ref = extracted.get(thisProjectRef)

    extracted get versionControlSystem match {
      case None => sys.error("No version control system is set!")
      case Some(vcs) => {
        lazy val remote: String = vcs.cmd("config", "branch.%s.remote" format vcs.currentBranch).!!.trim
        lazy val url: String = vcs.cmd("ls-remote", "--get-url", remote).!!.trim
        if (vcs.cmd("clone", "-b", "gh-pages", url, "target/gh-pages").! != 0)
          sys.error("Couldn't generate API docs, because this repo doesn't have gh-pages branch")
        else {
          val ghpagesDir = extracted.get(baseDirectory) / "target" / "gh-pages"
          val newSt = reapply(Seq(
              target in (Compile, doc) := ghpagesDir / "docs" / "api" / extracted.get(version).stripSuffix("-SNAPSHOT")
            ), st)
          val lastSt = extracted.runAggregated(doc in Compile in ref, newSt)

          val ghpages = Git.mkVcs(ghpagesDir)
          ghpages.add("docs") ! lastSt.log
          ghpages.commit("Updated API docs for sources commit: " + vcs.currentHash) ! lastSt.log
          ghpages.cmd("push") ! lastSt.log

          lastSt
        }
      }
    }
  }

}
